addons:
  apt:
    packages:
    - lftp
    - lib32z1
    - lib32stdc++6

language: sourcepawn

sudo: false

env:
  - VERSION=1.8
  - VERSION=1.9

script:
  - 'bash ci/test.sh; fi'

notifications:
    email: false