sudo: false

addons:
  apt:
    packages:
    - lftp
    - lib32z1
    - lib32stdc++6

language: c

env:
  - VERSION=1.8
  - VERSION=1.9
  
script:
  - 'bash ci/test.sh $VERSION; fi'

notifications:
    email: false