#Use the new container-based infrastructure
sudo: false
language: sourcepawn

#Install some apt packages needed for spcomp
addons:
  apt_packages:
    - lib32stdc++6

#And compile!
before_script:
  - wget "http://www.sourcemod.net/latest.php?version=1.8&os=linux" -O game/sourcemod-$SOURCEMOD-linux.tar.gz
  - cd game
  - tar -xzf sourcemod-$SOURCEMOD-linux.tar.gz
  - cd addons/sourcemod/scripting/
  - chmod +x spcomp

script:
  - ./compile.sh VipBonus.sp
  - mkdir ../plugins
  - mv VipBonus.smx ../plugins